# Generated by Django 4.1 on 2022-08-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('parentesco', models.CharField(max_length=40)),
                ('fecha_de_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('nota', models.CharField(max_length=40)),
            ],
        ),
    ]
