# Generated by Django 4.1 on 2022-08-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='fecha_de_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
