# Generated by Django 4.1 on 2022-08-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_alter_familia_fecha_de_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
