# Generated by Django 4.1 on 2022-08-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_familia_edad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Familia',
            new_name='Familiar',
        ),
    ]
