# Generated by Django 4.1 on 2022-08-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_auto_delete_familiar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=20)),
                ('fecha_lanzamiento', models.DateField()),
                ('velocidad_maxima', models.IntegerField()),
                ('transmision_automatica', models.CharField(max_length=10)),
                ('transmision_manual', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField()),
                ('area', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('continente', models.CharField(max_length=20)),
                ('empresas_automotrices', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Auto',
        ),
    ]
